steps:
- id: 'Deploy application to cluster'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.17.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    skaffold render -f=skaffold.yaml --default-repo=gcr.io/ejmadkins-refinitiv;
  dir: 'cloud-build-skaffold'