steps:
- id: 'Deploy application to cluster'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.17.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - >
    skaffold run -f=skaffold.yaml;
# Add more power, and more time, for heavy Skaffold build
timeout: '3600s'
options:
  machineType: 'N1_HIGHCPU_8'