steps:

- id: 'Deploy application to cluster'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.17.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
     skaffold render -f=skaffold.yaml -p=prod --loud=true --output=kubernetes-manifests/deploy/k8s-manifests.yaml
  dir: 'cloud-build-skaffold'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Clone env repository
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud source repos clone cloudbuild-skaffold-env && \
    cd cloudbuild-skaffold-env && \
    git checkout candidate && \
    git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
  
- name: 'gcr.io/cloud-builders/gcloud'
  id: Copy manifest to cloudbuild-skaffold-env
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     cp kubernetes-manifests/deploy/k8s-manifests.yaml cloudbuild-skaffold-env/k8s-manifests.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    cd cloudbuild-skaffold-env && \
    git add k8s-manifests.yaml && \
    git commit -m "Deploying image ${SHORT_SHA}
    Built from commit ${COMMIT_SHA} of repository hello-cloudbuild-app
    Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
    git push origin candidate