apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: cca45369-cbf8-459d-853e-74f20946e74c
  name: hello-world-dev-remote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        app.kubernetes.io/managed-by: skaffold
        skaffold.dev/run-id: cca45369-cbf8-459d-853e-74f20946e74c
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/ejmadkins-refinitiv/hello-world/hello-world:a930663@sha256:f564d3c429d037d1e0bc0d3aeaf7ca0e695cb468c4ad600e94fb18ed352412c8
        name: hello-world
