apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
    app.kubernetes.io/managed-by: skaffold
    env: prod
    skaffold.dev/run-id: cb6f6825-7a87-413b-9d74-a9bb112bbb89
  name: hello-world-dev-remote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        app.kubernetes.io/managed-by: skaffold
        skaffold.dev/run-id: cb6f6825-7a87-413b-9d74-a9bb112bbb89
    spec:
      containers:
      - image: europe-west2-docker.pkg.dev/ejmadkins-refinitiv/hello-world/hello-world:76d6026@sha256:b8c486e8ceb3629359ae5f652836883b62a339b82a8f1ea9f813d3d58a931076
        name: hello-world
