apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: hello-world

build:
  artifacts:
  - image: europe-west2-docker.pkg.dev/ejmadkins-dev-workflow-demos/remote-registry/hello-world
    context: .
    jib: {}
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  googleCloudBuild:
    projectId: ejmadkins-dev-workflow-demos

profiles:
- name: staging
  deploy:
    kustomize:
      paths:
      - kubernetes-manifests/overlays/staging
- name: prod
  deploy:
    kustomize:
      paths:
      - kubernetes-manifests/overlays/prod
