apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: hello-world

build:
  artifacts:
  - image: europe-west2-docker.pkg.dev/ejmadkins-refinitiv/hello/hello
    context: .
    jib: {}
  tagPolicy:
    sha256: {}
  googleCloudBuild: {}
