apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: hello-world

build:
  artifacts:
  - image: europe-west2-docker.pkg.dev/ejmadkins-refinitiv/hello-world/hello-world
    context: .
    jib: {}
  tagPolicy:
    gitCommit: {}
  googleCloudBuild:
    projectId: ejmadkins-refinitiv

profiles:
- name: staging
  deploy:
    kustomize:
      paths:
      - kubernetes-manifests/overlays/staging
- name: prod
  deploy:
    kustomize:
      paths:
      - kubernetes-manifests/overlays/prod
