apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: hello-world
build:
  artifacts:
  - image: europe-west2-docker.pkg.dev/ejmadkins-refinitiv/sessions/hello-world
    context: .
    jib: {}

deploy:
  kustomize:
    paths:
    - kubernetes-manifests/base

profiles:
  - name: local
    build:
      local:
        push: false
      tagPolicy:
        sha256: {}
    deploy:
      kustomize:
        paths:
        - kubernetes-manifests/overlays/dev
    activation:
    - kubeContext: docker-desktop