apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: hello-world

build:
  artifacts:
  - image: hello-world
    context: .
    jib: {}

deploy:
  kustomize:
    paths:
    - kubernetes-manifests/base

profiles:
  - name: local
    build:
      local:
        push: false
      tagPolicy:
        sha256: {}
    deploy:
      kustomize:
        paths:
        - kubernetes-manifests/overlays/dev-local
    activation:
    - kubeContext: docker-desktop
  - name: remote
    build:
      artifacts:
      - image: <YOUR-REGISTRY>
        context: .
        jib: {}
      tagPolicy:
        sha256: {}
      googleCloudBuild:
        projectId: <YOUR-GCP-PROJECT-ID>
    deploy:
      kustomize:
        paths:
        - kubernetes-manifests/overlays/dev-remote
    activation:
    - kubeContext: <YOUR-CONTEXT>